### ISSUE TITLE
Custom CA not recognized by pelorus pods (grafana and prometheus)

### ISSUE THREAD

**Issue by kevin-anderson-redhat** [redhat-cop/pelorus#91]
Attempts to login to prometheus and grafana fail with Error Page 500 Internal Error
Logs indicate that 
oauth fails with "certificate signed by unknown authority"

**Comment by etsauer** [comment]
This is something we'll have to fix in our helm chart, but for now the proper workaround is to:

1. Create an empty ConfigMap in the `pelorus` namespace:
```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    config.openshift.io/inject-trusted-cabundle: true
  name: cluster-ca-bundle
data:
```
2. Add a volume and volumeMount to the `prometheus/pelorus-prometheus` resource in the `pelorus` namespace:
```
  ...
  containers:
    name: prometheus-proxy
    ...
    volumeMounts:
    ...
    - mountPath: /etc/pki/ca-trust/extracted/pem/
      name: prometheus-trusted-ca-bundle
      readOnly: true
  ...
  volumes:
  ...
  - configMap:
      items:
      - key: ca-bundle.crt
        path: tls-ca-bundle.pem
      name: prometheus-trusted-ca-bundle-39man1pbaa8jq
      optional: true
    name: prometheus-trusted-ca-bundle
```

References: https://docs.openshift.com/container-platform/4.4/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki

**Comment by etsauer** [comment]
This should fix the prometheus component, but since the thanos-sidecar container is added by the operator, we need to figure out how to control that

**Comment by kevin-anderson-redhat** [comment]
Does the issue at the following link mean that the grafana-operator is a not easily resolved problem as well? https://github.com/integr8ly/grafana-operator/issues/190

**Comment by garethahealy** [comment]
@robbbbh ; did you have to do this for our prev customer?
- https://github.com/redhat-cop/pelorus/issues/91#issuecomment-642888495

**Comment by kevin-anderson-redhat** [comment]
@etsauer We were not able to get grafana to operate.  Still getting an untrusted cert failure in the grafana-proxy container.
